/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jni_md.h"
/* Header for class com_inveno_jni_CityHash */

#ifndef _Included_com_inveno_jni_CityHash
#define _Included_com_inveno_jni_CityHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inveno_jni_CityHash
 * Method:    cityHash32
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_com_inveno_jni_CityHash_cityHash32
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_inveno_jni_CityHash
 * Method:    cityHash64
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_com_inveno_jni_CityHash_cityHash64
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_inveno_jni_CityHash
 * Method:    cityHash128
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_com_inveno_jni_CityHash_cityHash128
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_inveno_jni_CityHash
 * Method:    cityHash256
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_com_inveno_jni_CityHash_cityHash256
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
